version: '3.3'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./data/db/data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=floq
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pguser
    ports:
      - 5432:5432
    expose:
      - 5432