package galois.llm.query;

import speedy.model.database.ITable;
import speedy.model.database.Tuple;

import java.util.List;

public interface IQueryExecutor {
    // TODO: In order to be more generic, switch ITable to IDatabase
    // TODO: The query should be generated by the actual executor: this allows for more flexibility...
    List<Tuple> execute(String query, ITable table);
}
